language: node_js
node_js:
  - 16

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker --version # print the version for logging
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker build -t udagram-api-user ./udagram-api-user
  - docker build -t udagram-api-frontend ./udagram-frontend
  - docker build -t udagram-api-reverseproxy ./udagram-reverseproxy
  - docker tag udagram-api-feed tewodros/udagram-api-feed:v0
  - docker tag udagram-api-user tewodros/udagram-api-user:v0
  - docker tag udagram-api-frontend tewodros/udagram-frontend:v0
  - docker tag udagram-api-reverseproxy tewodors/udagram-reverseproxy:v0

# Tasks to perform after the process is successful. Formatting the Docker username and password as below enables you to programmatically log in without having the password exposed in logs.
after_success:
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- docker push tewodros/udagram-api-feed:v0
- docker push tewodros/udagram-api-user:v0
- docker push tewodros/udagram-frontend:v0
- docker push tewodors/udagram-reverseproxy:v0
