apiVersion: v1
kind: Service
metadata:
  name: udagram-backend-user
  labels:
    app: udagram-backend-user
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: udagram-backend-user