apiVersion: v1
kind: Service
metadata:
  name: udagram-reverseproxy
  labels:
    service: udagram-reverseproxy
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    service: udagram-reverseproxy
  type: LoadBalancer
